# Generated by Django 3.2.6 on 2021-09-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('Activities', 'Activities'), ('Personal', 'Personal'), ('Food', 'Food')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Activities', 'Activities'), ('Personal', 'Personal'), ('Food', 'Food'), ('Recibos', 'Recibos'), ('Cate', 'Cate'), ('Arriendo', 'Arriendo'), ('Proyectos', 'Proyectos'), ('Compartidos', 'Compartidos')], max_length=50, null=True),
        ),
    ]
