# Generated by Django 3.2.6 on 2021-09-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210901_1945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
