# Generated by Django 3.2.6 on 2021-09-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_delete_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('category', models.CharField(choices=[('Activities', 'Activities'), ('Personal', 'Personal'), ('Food', 'Food'), ('Recibos', 'Recibos'), ('Cate', 'Cate'), ('Arriendo', 'Arriendo'), ('Proyectos', 'Proyectos'), ('Compartidos', 'Compartidos')], max_length=50, null=True)),
            ],
        ),
    ]
